### ISSUE TITLE
Update the README.md for the packages

### ISSUE THREAD

**Issue by o-murphy** [o-murphy/py_ballisticcalc#31]

**Comment by dbookstaber** [comment]
# Installation examples

pure python
>pip install py_ballisticcalc

with binary modules
>pip install py_ballisticcalc[exts]

with pyplot and pandas
>pip install py_ballisticcalc[graph]

with binary modules and pandas
>pip install py_ballisticcalc[exts,graph]

**Comment by o-murphy** [comment]
README.md updated in #39
